# Default configuration file for DiSky
# If you need more config options, ask us on Discord!
# > LINKS <
# Discord: https://disky.itsthesky.info/?page=discord
# Docs: https://disky.itsthesky.info/?page=docs

# THIS IS A BETA FEATURE !!!
# READ THE WIKI BEFORE ENABLING !!!
# SLASH COMMAND WIKI: https://github.com/SkyCraft78/DiSky/wiki/Slash-Commands
SlashCommand:
  Enabled: false
  # SlashCommands take like an hour to be updated on Discord.
  # However, we can send multiple command at once, and all of them will be updated.
  # If false, single command builders can't be registered, needs a list of commands.
  AllowSingle: false

# Intents managing when DiSky login a new Discord bot.
# Keep in mind if you disable some which are enabled by default,
# Some features of DiSky won't work!
Intents:
  # Default
  GUILD_MEMBERS: true
  GUILD_BANS: true
  GUILD_EMOJIS: true
  GUILD_WEBHOOKS: true
  GUILD_INVITES: true
  GUILD_VOICE_STATES: true
  GUILD_MESSAGE_REACTIONS: true
  GUILD_MESSAGE_TYPING: true
  DIRECT_MESSAGES: true
  GUILD_PRESENCES: true
  GUILD_MESSAGES: true
  # Plus
  GUILD_INTEGRATIONS: false
  DIRECT_MESSAGE_REACTIONS: false
  DIRECT_MESSAGE_TYPING: false

# This is for handling Discord & DiSky errors.
# It will enable the print stack (advanced debug)
# for specific errors. Only enable this if a support
# member asks you to do so :)
HandleErrors:
  NullPointerException: false
  InsufficientPermissionException: false

# Enable or disable the token of bot expression.
# It's mainly to avoid token leakers like with the
# OP / Permissions commands ('!')
TokenExpression: true