name: DiSky
version: 2.2
api-version: 1.13
main: info.itsthesky.disky.DiSky
author: ItsTheSky
description: Skript addon which allows you to interact with Discord through Skript.
website: https://disky.itsthesky.info/
softdepend:
  - Skript
